roboclaw_node:
  ros__parameters:
    dev: '/dev/serial/by-id/usb-Basicmicro_Inc._USB_Roboclaw_2x30A-if00'
    baud: 460800
    address: 128

    # Movement parameters
    max_speed_linear: 4.0
    max_speed_angular: 1.0
    stop_if_idle: True
    idle_timeout: 0.5

    # Odometry parameters
    ticks_per_meter: 3802.4
    ticks_per_rotation: 2780
    base_width: 0.52  # before: 0.315

    # PID parameters
    custom_pid: True
    p_constant: 3.0
    i_constant: 0.42
    d_constant: 0.0
    qpps: 6000

    # Publish parameters
    odom_rate: 20
    elec_rate: 10
    publish_odom: True
    publish_encoders: True
    publish_elec: True
    publish_tf: False
